features:
      top_secret:
          strategy: ip_whitelist
          variants: [enabled, disabled]
          options:
              whitelist: [127.0.0.1, 10.2.3.5]

strategies:
    ip_whitelist:
         voter: "context.current_ip in options.whitelist"